# Simple GitLab Runner Test

simple-test:
  image: alpine:latest
  script:
    - echo "Testing GitLab Runner connectivity"
    - echo "Runner ID is $CI_RUNNER_ID"
    - echo "Project is $CI_PROJECT_NAME"
    - echo "Branch is $CI_COMMIT_REF_NAME"
    - echo "Runner is working correctly"
    - date
    - whoami
  rules:
    - when: always