stages:
  - test
  - build
  - package

variables:
  NODE_VERSION: "18"
  CACHE_KEY: "${CI_COMMIT_REF_SLUG}-yarn-cache"

.yarn_template: &yarn_template
  image: node:${NODE_VERSION}-alpine
  cache:
    key: $CACHE_KEY
    paths:
      - .yarn/cache/
      - node_modules/
  before_script:
    - corepack enable
    - corepack prepare yarn@4.0.2 --activate
    - yarn install --immutable

# Test stage
lint:
  <<: *yarn_template
  stage: test
  script:
    - yarn lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test:
  <<: *yarn_template
  stage: test
  script:
    - yarn test
    - yarn test:coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - coverage/
    expire_in: 30 days
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

type_check:
  <<: *yarn_template
  stage: test
  script:
    - yarn type-check
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Build stage
build:
  <<: *yarn_template
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist/
      - lib/
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Package stage
package:
  <<: *yarn_template
  stage: package
  dependencies:
    - build
  script:
    - yarn pack
  artifacts:
    paths:
      - "*.tgz"
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG

# Security and quality checks
security_scan:
  <<: *yarn_template
  stage: test
  script:
    - yarn npm audit
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Deploy to npm (only on tags)
deploy_npm:
  <<: *yarn_template
  stage: package
  dependencies:
    - build
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - yarn npm publish
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
