stages:
  - test
  - build
  - package

variables:
  BUN_VERSION: "1.1.25"
  CACHE_KEY: "${CI_COMMIT_REF_SLUG}-node-modules"

.bun_template: &bun_template
  image: oven/bun:${BUN_VERSION}-alpine
  cache:
    key: $CACHE_KEY
    paths:
      - node_modules/
  before_script:
    - bun install --frozen-lockfile

# Test stage
lint:
  <<: *bun_template
  stage: test
  script:
    - bun run lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test:
  <<: *bun_template
  stage: test
  script:
    - bun run test
    - bun run test:coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - coverage/
    expire_in: 30 days
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

type_check:
  <<: *bun_template
  stage: test
  script:
    - bun run type-check
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Build stage
build:
  <<: *bun_template
  stage: build
  script:
    - bun run build
  artifacts:
    paths:
      - dist/
      - lib/
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Package stage
package:
  <<: *bun_template
  stage: package
  dependencies:
    - build
  script:
    - bun pack
  artifacts:
    paths:
      - "*.tgz"
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG

# Security and quality checks
security_scan:
  <<: *bun_template
  stage: test
  script:
    - bun audit
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Deploy to npm (only on tags)
deploy_npm:
  <<: *bun_template
  stage: package
  dependencies:
    - build
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - bun publish
  rules:
    - if: $CI_COMMIT_TAG
      when: manual