# Simple GitLab Runner Test
# This creates a basic job to test runner functionality

simple-test:
  image: alpine:latest
  script:
    - echo "Testing GitLab Runner connectivity"
    - echo "Runner ID: $CI_RUNNER_ID"
    - echo "Project: $CI_PROJECT_NAME"
    - echo "Branch: $CI_COMMIT_REF_NAME"
    - echo "Runner is working correctly!"
    - date
    - whoami
  rules:
    - when: always